
/**
* This code is generated by Vespa.
* Do not edit this file directly.
* Instead, make changes to the *.hsl files and regenerate the code.
* See the Vespa documentation for more information.
*/


export type Image = {
	alt: string;
	height: number;
	url: string;
	width: number;
};