
/**
* This code is generated by Vespa.
* Do not edit this file directly.
* Instead, make changes to the *.hsl files and regenerate the code.
* See the Vespa documentation for more information.
*/


import { Metadata, BaseRepository } from "@hiveops/core";


export type PostData = {
  body: string;
  title: string;
  userId: string;
};

export type Post = Metadata & PostData;

export class PostRepository extends BaseRepository<PostData, Post> {
  constructor() {
    super("Post");
  }
}

export const postRepository = new PostRepository();