
/**
* This code is generated by Vespa.
* Do not edit this file directly.
* Instead, make changes to the *.hsl files and regenerate the code.
* See the Vespa documentation for more information.
*/


export enum UserRole {
  ADMIN = 1,
  USER = 2,
}