
/**
* This code is generated by Vespa.
* Do not edit this file directly.
* Instead, make changes to the *.hsl files and regenerate the code.
* See the Vespa documentation for more information.
*/


import { Metadata, BaseRepository } from "@hiveops/core"; 
import { Image } from "./image"; 
import { Person } from "./person"; 
import { UserRole } from "./user-role";


export type UserData = Person & {
  email: string;
  isActive: boolean;
  lastLogin: Date;
  profileImage?: Image;
  role: UserRole;
};

export type User = Metadata & UserData;

export class UserRepository extends BaseRepository<UserData, User> {
  constructor() {
    super("User");
  }
}

export const userRepository = new UserRepository();